# Generated by Django 4.2.24 on 2026-02-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "title_ar",
                    models.CharField(max_length=200, null=True, verbose_name="Title"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, null=True, verbose_name="Title"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "description_ar",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "description_en",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Location"
                    ),
                ),
                (
                    "location_ar",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Location"
                    ),
                ),
                (
                    "location_en",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Location"
                    ),
                ),
                ("year", models.IntegerField(default=2024, verbose_name="Year")),
                (
                    "image",
                    models.ImageField(upload_to="projects/", verbose_name="Main Image"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
    ]
