# Generated by Django 4.2.24 on 2026-04-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="description_ar",
        ),
        migrations.RemoveField(
            model_name="project",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="project",
            name="location_ar",
        ),
        migrations.RemoveField(
            model_name="project",
            name="location_en",
        ),
        migrations.RemoveField(
            model_name="project",
            name="title_ar",
        ),
        migrations.RemoveField(
            model_name="project",
            name="title_en",
        ),
    ]
