# Generated by Django 4.2.24 on 2026-02-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "title_ar",
                    models.CharField(max_length=100, null=True, verbose_name="Title"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=100, null=True, verbose_name="Title"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="certificates/", verbose_name="Certificate Image"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "description_ar",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Certificate",
                "verbose_name_plural": "Certificates",
            },
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "title_ar",
                    models.CharField(max_length=200, null=True, verbose_name="Title"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, null=True, verbose_name="Title"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("content", models.TextField(verbose_name="Content")),
                ("content_ar", models.TextField(null=True, verbose_name="Content")),
                ("content_en", models.TextField(null=True, verbose_name="Content")),
                ("image", models.ImageField(upload_to="news/", verbose_name="Image")),
                (
                    "published_date",
                    models.DateField(auto_now_add=True, verbose_name="Published Date"),
                ),
            ],
            options={
                "verbose_name": "News Article",
                "verbose_name_plural": "News Articles",
                "ordering": ["-published_date"],
            },
        ),
    ]
