# Generated by Django 4.2.24 on 2026-04-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media_center", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="description_ar",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="title_ar",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="newsarticle",
            name="content_ar",
        ),
        migrations.RemoveField(
            model_name="newsarticle",
            name="content_en",
        ),
        migrations.RemoveField(
            model_name="newsarticle",
            name="title_ar",
        ),
        migrations.RemoveField(
            model_name="newsarticle",
            name="title_en",
        ),
    ]
