# Generated by Django 4.2.24 on 2026-04-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description_ar",
        ),
        migrations.RemoveField(
            model_name="category",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="category",
            name="name_ar",
        ),
        migrations.RemoveField(
            model_name="category",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description_ar",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="product",
            name="features_ar",
        ),
        migrations.RemoveField(
            model_name="product",
            name="features_en",
        ),
        migrations.RemoveField(
            model_name="product",
            name="name_ar",
        ),
        migrations.RemoveField(
            model_name="product",
            name="name_en",
        ),
    ]
